In [21]:
# importing all my functions
import acquired as a
import prepare as p
import model as m
import created_functions as cf

# data manipulation
import numpy as np
import pandas as pd

# importing knn model
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
# importing the titanic data
df = a.get_titanic_data()

this file exists, reading csv


In [3]:
df.head()

passenger_id  survived  pclass     sex   age  sibsp  parch  \
Unnamed: 0                                                               
0                      0         0       3    male  22.0      1      0   
1                      1         1       1  female  38.0      1      0   
2                      2         1       3  female  26.0      0      0   
3                      3         1       1  female  35.0      1      0   
4                      4         0       3    male  35.0      0      0   

               fare embarked  class deck  embark_town  alone  
Unnamed: 0                                                    
0            7.2500        S  Third  NaN  Southampton      0  
1           71.2833        C  First    C    Cherbourg      0  
2            7.9250        S  Third  NaN  Southampton      1  
3           53.1000        S  First    C  Southampton      0  
4            8.0500        S  Third  NaN  Southampton      1

In [4]:
# cleaning the data in the function
df = p.clean_titanic(df)


In [5]:
df.head()

passenger_id  survived pclass     sex  sibsp  parch     fare  \
Unnamed: 0                                                                 
0                      0         0      3    male      1      0   7.2500   
1                      1         1      1  female      1      0  71.2833   
2                      2         1      3  female      0      0   7.9250   
3                      3         1      1  female      1      0  53.1000   
4                      4         0      3    male      0      0   8.0500   

            embark_town  alone  
Unnamed: 0                      
0           Southampton      0  
1             Cherbourg      0  
2           Southampton      1  
3           Southampton      0  
4           Southampton      1

In [6]:
# splitting the data into train, validate, test
train, validate, test = p.splitting_data(df, 'survived')

In [7]:
# preproccess the data into encoded
train, validate, test = m.preprocess_titanic(train,validate,test)

In [8]:
train.head()

survived pclass  sibsp  parch      fare  alone  sex_male  \
Unnamed: 0                                                             
776                0      3      0      0    7.7500      1         1   
829                1      1      0      0   80.0000      1         0   
215                1      1      1      0  113.2750      0         0   
258                1      1      0      0  512.3292      1         0   
129                0      3      0      0    6.9750      1         1   

            sex_female  is_queenstown  is_southampton  
Unnamed: 0                                             
776                  0              1               0  
829                  1              0               1  
215                  1              0               0  
258                  1              0               0  
129                  0              0               1

In [9]:
# checking the split
train.shape, validate.shape, test.shape

((534, 10), (178, 10), (179, 10))

In [10]:
# create X and y versions
X_train = train.drop(columns=['survived'])
y_train = train.survived

X_validate = validate.drop(columns=['survived'])
y_validate = validate.survived

X_test = test.drop(columns=['survived'])
y_test = test.survived

In [11]:
# create baseline to compare to
y_train.value_counts()

survived
0    329
1    205
Name: count, dtype: int64

In [12]:
y_train.mode()

0    0
Name: survived, dtype: int64

>my baseline prediction is they didnt survive

In [13]:
# baseline accuracy
y_train.value_counts(normalize=True)[0]

0.6161048689138576

>67% is my baseline accuracy

In [14]:
# CREATE THE TABLE
knn = KNeighborsClassifier()

In [15]:
# FIT THE MODEL ONLY ON TRAIN
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [16]:
# USE THE MODEL
predicted = knn.predict(X_train)
predicted[:10]

array([0, 1, 1, 1, 0, 0, 1, 0, 1, 0])

In [17]:
# accuracy
knn.score(X_train, y_train)

0.8220973782771536

In [18]:
# evaluating the model
print(classification_report(y_train, predicted))

              precision    recall  f1-score   support

           0       0.84      0.87      0.86       329
           1       0.78      0.74      0.76       205

    accuracy                           0.82       534
   macro avg       0.81      0.81      0.81       534
weighted avg       0.82      0.82      0.82       534


In [19]:
# confusion_matrix
print(confusion_matrix(y_train, predicted))

[[287  42]
 [ 53 152]]


In [22]:
# using created function for printout
cf.print_classification_metrics(y_train, predicted)

Classification Metrics:
Accuracy: 0.82
True Positive Rate: 0.74
False Positive Rate: 0.13
True Negative Rate: 0.87
False Negative Rate: 0.26
Precision: 0.78
Recall: 0.74
F1 Score: 0.76

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.87      0.86       329
           1       0.78      0.74      0.76       205

    accuracy                           0.82       534
   macro avg       0.81      0.81      0.81       534
weighted avg       0.82      0.82      0.82       534


In [23]:
import created_functions as cf

In [25]:
cf.run_knn_and_evaluate(X_train, y_train, n_neighbors=10)

KNN Model with 10 Neighbors
Accuracy on Training Data: 0.80
First 10 Predictions: [0 1 1 1 0 0 1 0 1 0]


(0.795880149812734,
 array([0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
        0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
        1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0